In [1]:
%matplotlib notebook

In [2]:
import scipy.stats as stats
import matplotlib as mpl
import matplotlib.pyplot as plt
import numpy as np
import plotly.graph_objects as go
import random as rand
from mpl_toolkits.mplot3d import Axes3D
import math
from matplotlib import cm
from scipy.special import betainc
from scipy.special import gamma
import matplotlib.pyplot as plt
from statistics import NormalDist
import numpy as np
import colorsys
import random
from matplotlib.tri import Triangulation
from mpl_toolkits.mplot3d.art3d import Poly3DCollection
from pymoo.core.problem import ElementwiseProblem
from pymoo.algorithms.moo.nsga2 import NSGA2
from pymoo.factory import get_sampling, get_crossover, get_mutation
from pymoo.factory import get_termination
from pymoo.optimize import minimize
import time
import pandas

In [3]:
data_012 = pandas.read_csv('output_certify_cifar10_012', sep = '	')
data_025 = pandas.read_csv('output_certify_cifar10_025', sep = '	')
data_050 = pandas.read_csv('output_certify_cifar10_050', sep = '	')
data_100 = pandas.read_csv('output_certify_cifar10_100', sep = '	')
data_100

     idx  label  predict  radius  correct            time
0      0      3       -1   0.000        0  0:00:27.681616
1     20      7       -1   0.000        0  0:00:28.043091
2     40      4       -1   0.000        0  0:00:28.531114
3     60      7        7   0.680        1  0:00:28.926177
4     80      8        8   1.160        1  0:00:28.801826
..   ...    ...      ...     ...      ...             ...
85  1700      5        2   0.452        0  0:00:28.814805
86  1720      4       -1   0.000        0  0:00:28.806248
87  1740      1       -1   0.000        0  0:00:28.826549
88  1760      0       -1   0.000        0  0:00:28.851192
89  1780      7       -1   0.000        0  0:00:28.872386

[90 rows x 6 columns]

In [4]:
mean_012 = data_012['radius'][data_012['correct'] == 1].mean()
mean_025 = data_025['radius'][data_025['correct'] == 1].mean()
mean_050 = data_050['radius'][data_050['correct'] == 1].mean()
mean_100 = data_100['radius'][data_025['correct'] == 1].mean()

In [5]:
avg_012 = (data_012[data_012['correct'] == 1].count()/data_012.count())['idx']
avg_025 = (data_025[data_025['correct'] == 1].count()/data_025.count())['idx']
avg_050 = (data_050[data_050['correct'] == 1].count()/data_050.count())['idx']
avg_100 = (data_100[data_100['correct'] == 1].count()/data_100.count())['idx']

In [6]:
data_012['time'] = pandas.to_datetime(data_012['time'])
data_012['seconds'] = data_012['time'].dt.hour * 3600 + data_012['time'].dt.minute*60 + data_012['time'].dt.second

data_025['time'] = pandas.to_datetime(data_025['time'])
data_025['seconds'] = data_025['time'].dt.hour * 3600 + data_025['time'].dt.minute*60 + data_025['time'].dt.second
data_050['time'] = pandas.to_datetime(data_050['time'])
data_050['seconds'] = data_050['time'].dt.hour * 3600 + data_050['time'].dt.minute*60 + data_050['time'].dt.second
data_100['time'] = pandas.to_datetime(data_100['time'])
data_100['seconds'] = data_100['time'].dt.hour * 3600 + data_100['time'].dt.minute*60 + data_100['time'].dt.second

In [7]:
time_012 = data_012['seconds'].mean()
time_025 = data_025['seconds'].mean()
time_050 = data_050['seconds'].mean()
time_100 = data_100['seconds'].mean()

In [8]:
up_rad_012 = data_012['radius'][data_012['correct'] == 1].max()
min_rad_012 = data_012['radius'][data_012['correct'] == 1].min()
up_rad_025 = data_025['radius'][data_025['correct'] == 1].max()
min_rad_025 = data_025['radius'][data_025['correct'] == 1].min()
up_rad_050 = data_050['radius'][data_050['correct'] == 1].max()
min_rad_050 = data_050['radius'][data_050['correct'] == 1].min()
up_rad_100 = data_100['radius'][data_100['correct'] == 1].max()
min_rad_100 = data_100['radius'][data_100['correct'] == 1].min()

In [9]:
data = pandas.DataFrame().assign(Sigma = [0.12, 0.25, 0.50, 1.00], pourcentage_prediction_correcte = [avg_012, avg_025, avg_050, avg_100], rayon_moyen = [mean_012,mean_025, mean_050, mean_100], rayon_max = [up_rad_012, up_rad_025, up_rad_050, up_rad_100], rayon_min = [min_rad_012, min_rad_025, min_rad_050, min_rad_100], temps_calcul_moyen_secondes = [time_012, time_025, time_050, time_100])

In [10]:
data

,Sigma,pourcentage_prediction_correcte,rayon_moyen,rayon_max,rayon_min,temps_calcul_moyen_secondes
0,0.12,0.852941,0.340738,0.457,0.01130,28.000000
1,0.25,0.791667,0.553032,0.953,0.01680,27.983333
2,0.50,0.729730,0.751107,1.910,0.00323,28.018018
3,1.00,0.488889,0.707319,3.040,0.01310,27.988889